### ISSUE TITLE
Make module pip installable

### ISSUE THREAD

**Issue by DanielSchuette** [PhilippSchuette/PID_pendulum#2]

**Comment by DanielSchuette** [comment]
Go the `pip` way dude.

**Comment by DanielSchuette** [comment]
![image](https://user-images.githubusercontent.com/36865868/57580593-ee6f1e00-74ab-11e9-9631-335675645f2a.png)

**Comment by PhilippSchuette** [comment]
Mark it zero, dude!

**Comment by DanielSchuette** [comment]
The process of running the web app is now as follows:

1. pull the latest repository
1. `make` to install the repository locally (this is required because otherwise everything in `PID_control.py` is invisible to `api/app.py` and one would need to mess with the `PYTHON_PATH`; this might not work because I explicitly called `python3` and `pip3` -> naming might be different on different machines)
1. `cd` into `api/` and `flask run` the server
1. visit `localhost:5000` to access the static `html`
1. `./req_api.sh` in another terminal window to make an API request to the `/api/v1` endpoint => flask's error logs will show what went wrong in `app.py`

The error is about instantiating the `Pendulum` class or calling the `.solve` method. I probably got the order of the parameters wrong. Thanks for debugging!
